server:
  port: 8888

name1: 开发环境
age1: 18
content1: "name:${name1},age:${age1}"


student:
  name: 开发环境
  age: 18
  

spring:    
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/wanghao?useUnicode=true&characterEncoding=utf-8
  jpa:
     hibernate:
        ddl-auto: update
        show-sql: true
